POST http://localhost:3000/api/v1/roles HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NTI0OWFkYzU4NjJlY2I0MGE5NDdhNCIsImVtYWlsIjoidGVzdDAyQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoidGVzdDAyIiwiaWF0IjoxNzUwMzU2MTEyLCJleHAiOjE3NTAzNTk3MTJ9.YR0Uh6KbCUCdAEs4ur_O3E8xoOf4Z0Xgg1a2LEC6PrM
Content-Type: application/json

{
  "name": "test"
}

###
GET http://localhost:3000/api/v1/roles HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NTI0OWFkYzU4NjJlY2I0MGE5NDdhNCIsImVtYWlsIjoidGVzdDAyQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoidGVzdDAyIiwiaWF0IjoxNzUwMzU2MTEyLCJleHAiOjE3NTAzNTk3MTJ9.YR0Uh6KbCUCdAEs4ur_O3E8xoOf4Z0Xgg1a2LEC6PrM

###
PUT http://localhost:3000/api/v1/roles/684b0abb87c98958bf6eb1ed HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NTI0OWFkYzU4NjJlY2I0MGE5NDdhNCIsImVtYWlsIjoidGVzdDAyQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoidGVzdDAyIiwiaWF0IjoxNzUwMzU2MTEyLCJleHAiOjE3NTAzNTk3MTJ9.YR0Uh6KbCUCdAEs4ur_O3E8xoOf4Z0Xgg1a2LEC6PrM
Content-Type: application/json

{
  "name": "prueba"
}

###
GET http://localhost:3000/api/v1/roles/684b0abb87c98958bf6eb1ed HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NTI0OWFkYzU4NjJlY2I0MGE5NDdhNCIsImVtYWlsIjoidGVzdDAyQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoidGVzdDAyIiwiaWF0IjoxNzUwMzU2MTEyLCJleHAiOjE3NTAzNTk3MTJ9.YR0Uh6KbCUCdAEs4ur_O3E8xoOf4Z0Xgg1a2LEC6PrM

###
DELETE http://localhost:3000/api/v1/roles/684b0abb87c98958bf6eb1ed HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NTI0OWFkYzU4NjJlY2I0MGE5NDdhNCIsImVtYWlsIjoidGVzdDAyQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoidGVzdDAyIiwiaWF0IjoxNzUwMzU2MTEyLCJleHAiOjE3NTAzNTk3MTJ9.YR0Uh6KbCUCdAEs4ur_O3E8xoOf4Z0Xgg1a2LEC6PrM